### ISSUE TITLE
Does it work? Chrome cancels fetch requests

### ISSUE THREAD

**Issue by strong-banana** [artemtam/cyber-yozh#10]
Thanks for the weapon 🦾

I was wondering whether the tool was working correctly, as Chrome shows all the fetch requests as "(canceled)"
Is this normal - and is there anything I could possibly do about? 

![Screenshot 2022-03-01 at 11 28 33](https://user-images.githubusercontent.com/100691575/156166046-cb00b258-0e23-46af-ab6e-a718dc3c9a78.png)

Cheers, greets from western europe & slava ukraina ✌️

**Comment by artemtam** [comment]
Thanks for reporting, was an awful typo on our side. Fixed already.

https://github.com/artemtam/cyber-yozh/issues/11#issuecomment-1055594062
