### ISSUE TITLE
Suspected memleak in Chrome

### ISSUE THREAD

**Issue by beaverdude** [artemtam/cyber-yozh#7]
Win10, Win11, the latest clean chrome, no extensions.
Memory which is allocated to chrome process constantly grows and eventually Windows kills the process (or chrome tab self-crashes)
More threads I select - faster an OOM happens. 

Does anyone see same behavior?

**Comment by artemtam** [comment]
I've seen some reports, so most likely the issue is valid. 
Any ideas where it could be?

**Comment by beaverdude** [comment]
yeah, I suspect that's the effect of increased size of Promises (with arguments) in an array due to added payload. 
It looks like a chrome's garbage collector doesn't cleanup after a promise is resolved/rejected and shifted out from an array, or maybe doesn't do it quickly enough. 
For the test I increased a payload size to 200kB and got OOM in a matter of minutes.

**Comment by artemtam** [comment]
Fixed in #8.
